name: API tests 🧪
on:  
  push:
  schedule: ## Schedule the job to run at 12.am daily.
    - cron: '0 12 * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          spec: |
            cypress/e2e/api/FGTS.cy.js
            cypress/e2e/api/INSS.cy.js
            cypress/e2e/api/CartaoBeneficio_RepresentanteLegal.cy.js
            cypress/e2e/api/INSS_RepresentanteLegal.cy.js
